version: 2.1
jobs:
  R-4_0:
    docker:
      - image: rocker/tidyverse:4.0.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
      - run:
          name: Install package dependencies
          command: |
            R -q -e ".libPaths()"
            R -q -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --no-manual *tar.gz
      - run:
          name: Run code coverage
          command: |
            R -q -e "install.packages(\"covr\", dependencies = TRUE, repos = \"https://cloud.r-project.org\")"
            R -q -e "covr::codecov(line_exclusions = list(\"R/api_client.R\", \"R/api_response.R\", \"R/dialect.R\", \"R/health_api.R\", \"R/health_check.R\", \"R/query_api.R\", \"R/query.R\", \"R/ready_api.R\", \"R/ready.R\", \"R/write_api.R\", \"R/zzz.R\"))"
          environment:
            MAKE: make -j 4
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"

  R-3_3:
    docker:
      - image: rstudio/r-base:3.3.3-bionic
    steps:
      - checkout
      - run:
          name: Install openssl
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq install -y software-properties-common
            sudo apt-add-repository 'deb http://security.ubuntu.com/ubuntu bionic-security main'
            sudo apt-get -qq install -y libssl-dev
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
      - run:
          name: Install package dependencies
          command: |
            R -q -e ".libPaths()"
            R -q -e "install.packages(c(\"httr\", \"bit64\", \"nanotime\", \"plyr\"), repos = \"https://cloud.r-project.org\")"
            R -q -e "install.packages(c(\"rlang\", \"magrittr\", \"testthat\", \"httptest\"), repos = \"https://cloud.r-project.org\")"
          environment:
            MAKE: make -j 4
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/opt/R/3.3.3/lib/R/library"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --no-manual *tar.gz

workflows:
  version: 2
  build:
    jobs:
      - R-4_0:
          name: test-4.0
      - R-3_3:
          name: test-3.3
