version: 2
jobs:
  "R-4.0":
    docker:
      - image: rocker/tidyverse:4.0.5
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --no-manual *tar.gz

  "R-3.3":
    docker:
      - image: rstudio/r-base:3.3.3-bionic
    steps:
      - checkout
      - run:
          name: Install openssl
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq install -y software-properties-common
            sudo apt-add-repository 'deb http://security.ubuntu.com/ubuntu bionic-security main'
            sudo apt-get -qq install -y libssl-dev
      - run:
          name: Install package dependencies
          command: |
            R -e "install.packages(c(\"httr\", \"bit64\", \"nanotime\", \"plyr\"), repos = \"https://cloud.r-project.org\")"
            R -e "install.packages(c(\"rlang\", \"magrittr\", \"testthat\", \"httptest\"), repos = \"https://cloud.r-project.org\")"
          environment:
            MAKE: make -j4
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --no-manual *tar.gz

workflows:
  version: 2
  build:
    jobs:
      - "R-4.0"
      - "R-3.3"
